### PR TITLE
Fix deprecation warning, close #23

### LINKED ISSUE #23: The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead
Reported by @donovanhiland in feross/eslint-config-standard#83

### PR DESCRIPTION
**Pull request by grxy**

### CODE REVIEW

**Review by Flet — APPROVED** [review]

**Comment by Flet** [comment]
This is merged, but only @feross can publish a new version :)

**Comment by feross** [comment]
LGTM, sorry for the delay! Giving publish rights to other contributors is on my todo list.

**Comment by feross** [comment]
Published as 4.0.2.

**Comment by grxy** [comment]
Thanks @feross!

**Pull request merged**
