### PR TITLE
Update jsx-quotes to prefer-double

### PR DESCRIPTION
**Pull request by kyeotic**
Per [this issue](https://github.com/feross/eslint-config-standard/issues/27#issuecomment-221763091)

### CODE REVIEW

**Comment by dcousens** [comment]
+1 from me

**Comment by pluma** [comment]
This overrides the rule present in eslint-config-standard (despite being a jsx rule). Should the rule be moved into this repo and removed in the other one or vice versa?

**Comment by kyeotic** [comment]
@pluma I didnt' even realize the the other one had the rule. I think @feross might have to make that decision. I can make another PR for eslint-config-standard if necessary

**Comment by dcousens** [comment]
I suspect its an artifact.  Its relevance to `jsx` means it should be here AFAIK.

**Comment by feross** [comment]
This is released as 2.0.0. I removed the `"jsx-quotes"` rule from `eslint-config-standard`.

**Pull request merged**
